#pragma once

#include "defines.h"

#include "../game/memory/memory.h"
#include "../math/math.h"

#include "vgui2/vpanel.h"
#include "vgui/isurface.h"
#include "cusercmd.h"
#include "utl_vector.h"
#include "convar.h"
#include "clientclass.h"
#include "cdll_int.h"
#include "cdll_client_int.h"
#include "cdll_engine_int.h"
#include "globalvars_base.h"
#include "ienginetrace.h"
#include "modelinfo.h"
#include "weapons.h"
#include "inetmessage.h"
#include "imaterial.h"
#include "imaterialvar.h"
#include "imaterialsystem.h"
#include "ivmodelrender.h"